version: '3'
services:
  eureka:
    image: minutaurus/sosikeureka:tag
    ports:
      - "8761:8761"
    networks:
      network1:
        ipv4_address: 172.20.0.3
    container_name: eureka-server
  api-gateway:
    image: minutaurus/sosikgateway:tag
    networks:
      network1:
        ipv4_address: 172.20.0.4
    ports:
      - "5056:5056"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://172.20.0.3:8761/eureka/
    depends_on:
      - eureka

  member-service:
    image: minutaurus/member-service:tag
    networks:
      network1:
        ipv4_address: 172.20.0.5
    ports:
      - "9000:9000"
    depends_on:
      - eureka
      - api-gateway
  # Redis Service
  redis:
    image:  minutaurus/redisimage:tag
    ports:
      - "6379:6379"  # Redis 포트 매핑
    volumes:
      - redis:/app  # Redis 데이터를 저장할 볼륨 매핑
    networks:
      network1:
        ipv4_address: 172.20.0.6

  # Mysql food data
  mysql-sosik-db:
    image: gommind/sosik-test-db
    volumes:
      - sosik-data:/var/lib/mysql
    ports:
      - "10000:3306"
    networks:
      network1:
        ipv4_address: 172.20.0.101


volumes:
  redis:
  # mysql food data
  sosik-data:

networks:
  network1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

